### ISSUE TITLE
Change Primary Button Text Color From Black to White

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#7]
You'll see the issue if you look at the big "Apply Now" button at the bottom of the landing. Bootstrap automatically sets the text color to black or white depending on the primary color (for contrast/accessibility).

![Image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/5be1c190-858c-4fe8-a23e-3643413e640d)

**Comment by vu-dylan** [comment]
Could be achieved by changing the CSS applied to the button's color. Here's the relevant HTML snippet:

```html
<button type="button" class="hvr-bounce-in  btn btn-primary mx-auto mb-5" data-aos="fade-up"
                style="--bs-btn-padding-y: 1.5rem; --bs-btn-padding-x: 1.7rem; --bs-btn-border-radius: 1.5rem; --bs-btn-font-size: 2.5rem;">
                <i class="bi bi-pen me-1"></i>
                Apply Now
            </button>
```

Could be accomplished by looking into one of the button's bootstrap classes: `class="hvr-bounce-in  btn btn-primary mx-auto mb-5"` or adding another class?

My PR might help, since it [changes the color of the navbar](https://github.com/uci-ieee/ops-webpages-2023-2024/pull/18)
